language: scala
scala:
  - 2.12.4
jdk:
  - oraclejdk8

script:
  - export CODACY_PROJECT_TOKEN=8b28cb32200f483b9b0b9688c8b99c5d
  - sbt "calculusJS/test"
  - sbt "calculusJVM/test"
  - sbt "lang/test"

notifications:
  email:
    - hejfelix@gmail.com

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ba2f1f37ff3f71b00991
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
