language: scala
scala:
  - 2.12.4
jdk:
  - oraclejdk8

script:
  - export CODACY_PROJECT_TOKEN=8b28cb32200f483b9b0b9688c8b99c5d
  - sbt calculusJS/test calculusJVM/test lang/test web/fastOptJS::webpack
  - ./bin/refresh_gh_pages.sh

deploy:
  edge:
    branch: v1.8.47
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  local-dir: deploy

notifications:
  email:
    - hejfelix@gmail.com

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ba2f1f37ff3f71b00991
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
